[phases.setup]
nixPkgs = ['bun', 'openssl_3']

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.prerender]
cmds = ['bun run db:generate']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bunx prisma db push --accept-data-loss && bun run start'

[variables]
NODE_ENV = 'production'
NEXT_TELEMETRY_DISABLED = '1'
