[build]
builder = "nixpacks"

[deploy]
startCommand = "bunx prisma db push --accept-data-loss && bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
